apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-web
  labels:
    app: staging-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staging-web
  template:
    metadata:
      labels:
        app: staging-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: staging-web
          image: ghcr.io/ekerette0852/production-devops-platform:3b0b425
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
